---
- name: Ensuring config directory exist
  ansible.builtin.file:
    path: "{{ alertmanager_config_dir }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: 0755
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ alertmanager_services }}"

- name: Find custom alertmanager custom template files
  local_action:
    module: find
    path: "{{ ansitheus_custom_config_dir }}/alertmanager/templates"
    pattern: "*.tmpl"
  run_once: true
  register: alertmanager_custom_template_files

- name: Ensuring custom template directory exist
  ansible.builtin.file:
    path: "{{ alertmanager_config_dir }}/templates/"
    state: "directory"
    mode: 0755
  when:
    - alertmanager_custom_template_files is defined and alertmanager_custom_template_files.files | length > 0

- name: Copying custom alertmanager custom template files if exists
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ alertmanager_config_dir }}/templates/{{ item.path | basename }}"
    mode: 0755
  register: alertmanager_custom_templates
  when:
    - alertmanager_custom_template_files is defined and alertmanager_custom_template_files.files | length > 0
  with_items: "{{ alertmanager_custom_template_files.files }}"

- name: Configure Alertmanager web
  ansible.builtin.copy:
    content: "{{ alertmanager_web_config | to_nice_yaml(indent=2, sort_keys=False) }}"
    dest: "{{ alertmanager_config_dir }}/web.yml"
    force: true
    mode: 0755

- name: Copying over alertmanager config file
  vars:
    service: "{{ alertmanager_services['alertmanager'] }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ alertmanager_config_dir }}/config.yml"
    mode: 0755
  register: alertmanager_config
  with_first_found:
    - "{{ ansitheus_custom_config_dir }}/alertmanager/{{ inventory_hostname }}/alertmanager.yml"
    - "{{ ansitheus_custom_config_dir }}/alertmanager/alertmanager.yml"
    - "{{ role_path }}/templates/alertmanager.yml.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool

- name: Validate alertmanager config
  vars:
    service_name: "alertmanager"
    service: "{{ alertmanager_services[service_name] }}"
  ansible.builtin.command: >
    /usr/bin/docker run --rm -v {{ alertmanager_config_dir }}:/etc/alertmanager {{ alertmanager_image }} sh -c 'amtool \
            check-config /etc/alertmanager/config.yml'
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool

# NOTE(kiennt26): Reloading the config by sending SIGHUP to the main process, instead of sending a POST request
#                 to the /-/reload endpoint, because the latter doesn't work when the basic auth is enabled.
#                 The password for the basic auth is encrypted using bcrypt, and I don't want to store the raw password
#                 The SIGHUP signal is sent to the process with PID 1 in the container, which is the main process.
- name: Reload alertmanager config
  vars:
    service_name: "alertmanager"
    service: "{{ alertmanager_services[service_name] }}"
  ansible.builtin.command: >
    /usr/bin/docker exec -i {{ alertmanager_container_name }} kill -SIGHUP 1
  register: result
  retries: 5
  delay: 20
  until: result.rc == 0
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool

- name: Check alertmanager containers
  community.general.docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    command: "{{ item.value.command }}"
    state: "{{ item.value.state }}"
    restart_policy: "{{ item.value.restart_policy }}"
    privileged: "{{ item.value.privileged }}"
    network_mode: "{{ item.value.network_mode }}"
    log_driver: "{{ item.value.log_driver }}"
    log_options: "{{ item.value.log_options }}"
    memory: "{{ item.value.memory }}"
    memory_swap: "{{ item.value.memory_swap }}"
    cpus: "{{ item.value.cpus }}"
    env: "{{ item.value.env }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ alertmanager_services }}"
